# Generated by Skyramp v1.3.29 on 2026-06-28 23:45:11.53778855 +0000 UTC m=+241.794175250
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output circuit_patch_invalid_dates_integration_test.py \
# 		--output-dir /home/runner/work/netbox/netbox/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/netbox/netbox/tests/skyramp/scenario_circuit-patch-invalid-dates.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8092")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    circuits = "8"

    # Request Body
    endpoint_4_POST_request_body = r'''{
        "name": "Provider-PatchTest",
        "slug": "provider-patchtest"
    }'''
    
    # Execute Request
    endpoint_4_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/circuits/providers/",
        method="POST",
        body=endpoint_4_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_4_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_4_POST_response, "name") == "Provider-PatchTest"
    assert skyramp.get_response_value(endpoint_4_POST_response, "slug") == "provider-patchtest"
    assert skyramp.get_response_value(endpoint_4_POST_response, "id") > 0

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "name": "CircuitType-PatchTest",
        "slug": "circuittype-patchtest"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/circuits/circuit-types/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "CircuitType-PatchTest"
    assert skyramp.get_response_value(endpoint_1_POST_response, "slug") == "circuittype-patchtest"
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") > 0

    # Request Body
    _provider_id = skyramp.get_response_value(endpoint_4_POST_response, "id")
    _type_id = skyramp.get_response_value(endpoint_1_POST_response, "id")
    endpoint_2_POST_request_body = '{{"cid": "CID-PATCH-001", "provider": {0}, "status": "active", "type": {1}}}'.format(_provider_id, _type_id)
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/circuits/circuits/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_2_POST_response, "cid") == "CID-PATCH-001"
    assert skyramp.get_response_value(endpoint_2_POST_response, "status") == "active"
    assert skyramp.get_response_value(endpoint_2_POST_response, "id") > 0

    # Request Body
    endpoint_3_PATCH_request_body = r'''{
        "install_date": "2025-06-01",
        "termination_date": "2024-01-01"
    }'''
    
    # Execute Request
    endpoint_3_PATCH_response = client.send_request(
        url=URL_localhost,
        path="/api/circuits/circuits/{circuits}/",
        method="PATCH",
        body=endpoint_3_PATCH_request_body,
        headers=headers,
        path_params={"circuits": circuits}
    )
    # Generated Assertions
    assert endpoint_3_PATCH_response.status_code == 400
    assert skyramp.get_response_value(endpoint_3_PATCH_response, "termination_date.0") == "The termination date cannot precede the installation date."
    assert skyramp.get_response_value(endpoint_3_PATCH_response, "termination_date.1") is None


if __name__ == "__main__":
    test_integration()
