# Generated by Skyramp v1.3.33 on 2026-07-08 02:14:37.691808167 +0000 UTC m=+214.444563072
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output circuit_update_termination_before_install_integration_test.py \
# 		--output-dir /home/runner/work/netbox/netbox/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/netbox/netbox/tests/skyramp/scenario_circuit_update_termination_before_install.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8092")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_4_POST_request_body = r'''{
        "name": "Skyramp Test Provider C",
        "slug": "skyramp-test-provider-c"
    }'''

    # Execute Request
    endpoint_4_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/circuits/providers/",
        method="POST",
        body=endpoint_4_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert endpoint_4_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_4_POST_response, "name") == "Skyramp Test Provider C"
    assert skyramp.get_response_value(endpoint_4_POST_response, "slug") == "skyramp-test-provider-c"
    assert skyramp.get_response_value(endpoint_4_POST_response, "id") > 0

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "name": "Skyramp Test Circuit Type C",
        "slug": "skyramp-test-circuit-type-c"
    }'''

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/circuits/circuit-types/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "Skyramp Test Circuit Type C"
    assert skyramp.get_response_value(endpoint_1_POST_response, "slug") == "skyramp-test-circuit-type-c"
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") > 0

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "cid": "SKY-CIRC-C-001",
        "install_date": "2024-01-01",
        "provider": 9021,
        "termination_date": "2025-06-01",
        "type": 9022
    }'''

    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/circuits/circuits/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers,
        data_override={
            "provider": skyramp.get_response_value(endpoint_4_POST_response, "id"),
            "type": skyramp.get_response_value(endpoint_1_POST_response, "id")
        }
    )

    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_2_POST_response, "cid") == "SKY-CIRC-C-001"
    assert skyramp.get_response_value(endpoint_2_POST_response, "install_date") == "2024-01-01"
    assert skyramp.get_response_value(endpoint_2_POST_response, "termination_date") == "2025-06-01"
    assert skyramp.get_response_value(endpoint_2_POST_response, "id") > 0

    # Request Body
    endpoint_3_PATCH_request_body = r'''{
        "termination_date": "2023-01-01"
    }'''

    # Execute Request
    endpoint_3_PATCH_response = client.send_request(
        url=URL_localhost,
        path="/api/circuits/circuits/{circuits}/",
        method="PATCH",
        body=endpoint_3_PATCH_request_body,
        headers=headers,
        path_params={"circuits": skyramp.get_response_value(endpoint_2_POST_response, "id")}
    )

    # Generated Assertions
    assert endpoint_3_PATCH_response.status_code == 400
    assert skyramp.get_response_value(endpoint_3_PATCH_response, "termination_date.0") == "The termination date cannot precede the installation date."
    assert skyramp.get_response_value(endpoint_3_PATCH_response, "termination_date.1") is None


if __name__ == "__main__":
    test_integration()
