# Generated by Skyramp v1.3.33 on 2026-07-08 02:14:30.834772212 +0000 UTC m=+207.587527097
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output circuit_create_termination_before_install_integration_test.py \
# 		--output-dir /home/runner/work/netbox/netbox/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/netbox/netbox/tests/skyramp/scenario_circuit_create_termination_before_install.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8092")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_3_POST_request_body = r'''{
        "name": "Skyramp Test Provider A",
        "slug": "skyramp-test-provider-a"
    }'''

    # Execute Request
    endpoint_3_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/circuits/providers/",
        method="POST",
        body=endpoint_3_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert endpoint_3_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_3_POST_response, "name") == "Skyramp Test Provider A"
    assert skyramp.get_response_value(endpoint_3_POST_response, "slug") == "skyramp-test-provider-a"
    assert skyramp.get_response_value(endpoint_3_POST_response, "id") > 0

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "name": "Skyramp Test Circuit Type A",
        "slug": "skyramp-test-circuit-type-a"
    }'''

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/circuits/circuit-types/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "Skyramp Test Circuit Type A"
    assert skyramp.get_response_value(endpoint_1_POST_response, "slug") == "skyramp-test-circuit-type-a"
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") > 0

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "cid": "SKY-CIRC-A-001",
        "install_date": "2025-06-01",
        "provider": 9001,
        "termination_date": "2024-01-01",
        "type": 9002
    }'''

    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/circuits/circuits/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers,
        data_override={
            "provider": skyramp.get_response_value(endpoint_3_POST_response, "id"),
            "type": skyramp.get_response_value(endpoint_1_POST_response, "id")
        }
    )

    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 400
    assert skyramp.get_response_value(endpoint_2_POST_response, "termination_date.0") == "The termination date cannot precede the installation date."
    assert skyramp.get_response_value(endpoint_2_POST_response, "termination_date.1") is None


if __name__ == "__main__":
    test_integration()
