# Generated by Skyramp v1.3.33 on 2026-07-08 02:14:32.608913977 +0000 UTC m=+209.361668862
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output circuit_create_valid_date_ordering_integration_test.py \
# 		--output-dir /home/runner/work/netbox/netbox/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/netbox/netbox/tests/skyramp/scenario_circuit_create_valid_date_ordering.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8092")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_3_POST_request_body = r'''{
        "name": "Skyramp Test Provider B",
        "slug": "skyramp-test-provider-b"
    }'''

    # Execute Request
    endpoint_3_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/circuits/providers/",
        method="POST",
        body=endpoint_3_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert endpoint_3_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_3_POST_response, "name") == "Skyramp Test Provider B"
    assert skyramp.get_response_value(endpoint_3_POST_response, "slug") == "skyramp-test-provider-b"
    assert skyramp.get_response_value(endpoint_3_POST_response, "id") > 0

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "name": "Skyramp Test Circuit Type B",
        "slug": "skyramp-test-circuit-type-b"
    }'''

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/circuits/circuit-types/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "Skyramp Test Circuit Type B"
    assert skyramp.get_response_value(endpoint_1_POST_response, "slug") == "skyramp-test-circuit-type-b"
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") > 0

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "cid": "SKY-CIRC-B-001",
        "install_date": "2024-01-01",
        "provider": 9011,
        "termination_date": "2025-06-01",
        "type": 9012
    }'''

    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/circuits/circuits/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers,
        data_override={
            "provider": skyramp.get_response_value(endpoint_3_POST_response, "id"),
            "type": skyramp.get_response_value(endpoint_1_POST_response, "id")
        }
    )

    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_2_POST_response, "cid") == "SKY-CIRC-B-001"
    assert skyramp.get_response_value(endpoint_2_POST_response, "install_date") == "2024-01-01"
    assert skyramp.get_response_value(endpoint_2_POST_response, "termination_date") == "2025-06-01"
    assert skyramp.get_response_value(endpoint_2_POST_response, "provider.id") == skyramp.get_response_value(endpoint_3_POST_response, "id")
    assert skyramp.get_response_value(endpoint_2_POST_response, "type.id") == skyramp.get_response_value(endpoint_1_POST_response, "id")
    assert skyramp.get_response_value(endpoint_2_POST_response, "id") > 0


if __name__ == "__main__":
    test_integration()
