# Generated by Skyramp v1.3.29 on 2026-06-28 23:45:10.088214384 +0000 UTC m=+240.344601084
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output circuit_valid_dates_integration_test.py \
# 		--output-dir /home/runner/work/netbox/netbox/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/netbox/netbox/tests/skyramp/scenario_circuit-valid-dates.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8092")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_3_POST_request_body = r'''{
        "name": "Provider-ValidDatesTest",
        "slug": "provider-validdatestest"
    }'''
    
    # Execute Request
    endpoint_3_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/circuits/providers/",
        method="POST",
        body=endpoint_3_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_3_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_3_POST_response, "name") == "Provider-ValidDatesTest"
    assert skyramp.get_response_value(endpoint_3_POST_response, "slug") == "provider-validdatestest"
    assert skyramp.get_response_value(endpoint_3_POST_response, "id") > 0

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "name": "CircuitType-ValidDatesTest",
        "slug": "circuittype-validdatestest"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/circuits/circuit-types/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "CircuitType-ValidDatesTest"
    assert skyramp.get_response_value(endpoint_1_POST_response, "slug") == "circuittype-validdatestest"
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") > 0

    # Request Body
    _provider_id = skyramp.get_response_value(endpoint_3_POST_response, "id")
    _type_id = skyramp.get_response_value(endpoint_1_POST_response, "id")
    endpoint_2_POST_request_body = '{{"cid": "CID-VALID-001", "install_date": "2024-01-01", "provider": {0}, "status": "active", "termination_date": "2025-06-01", "type": {1}}}'.format(_provider_id, _type_id)
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/circuits/circuits/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_2_POST_response, "cid") == "CID-VALID-001"
    assert skyramp.get_response_value(endpoint_2_POST_response, "status") == "active"
    assert skyramp.get_response_value(endpoint_2_POST_response, "install_date") == "2024-01-01"
    assert skyramp.get_response_value(endpoint_2_POST_response, "termination_date") == "2025-06-01"
    assert skyramp.get_response_value(endpoint_2_POST_response, "id") > 0


if __name__ == "__main__":
    test_integration()
