# Generated by Skyramp v1.3.29 on 2026-06-25 22:32:07.282274084 +0000 UTC m=+290.830949371
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output manufacturer_lifecycle_integration_test.py \
# 		--output-dir /home/runner/work/netbox/netbox/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/netbox/netbox/tests/skyramp/scenario_manufacturer-lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8092")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "name": "TestbotMfr-20260625",
        "slug": "testbot-mfr-20260625"
    }'''

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/dcim/manufacturers/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "TestbotMfr-20260625"
    assert skyramp.get_response_value(endpoint_1_POST_response, "slug") == "testbot-mfr-20260625"
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") > 0
    assert skyramp.get_response_value(endpoint_1_POST_response, "url").startswith("http://")
    manufacturers = str(skyramp.get_response_value(endpoint_1_POST_response, "id"))

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/dcim/manufacturers/{manufacturers}/",
        method="GET",
        headers=headers,
        path_params={"manufacturers": manufacturers}
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_2_GET_response, "id") == skyramp.get_response_value(endpoint_1_POST_response, "id")
    assert skyramp.get_response_value(endpoint_2_GET_response, "name") == "TestbotMfr-20260625"
    assert skyramp.get_response_value(endpoint_2_GET_response, "slug") == "testbot-mfr-20260625"

    # Execute Request
    endpoint_2_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/dcim/manufacturers/{manufacturers}/",
        method="DELETE",
        headers=headers,
        path_params={"manufacturers": manufacturers}
    )
    # Generated Assertions
    assert endpoint_2_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
