# Generated by Skyramp v1.3.33 on 2026-07-08 02:20:05.469833445 +0000 UTC m=+522.584357849
# Command: skyramp generate contract rest http://localhost:8092/api/circuits/providers/{id}/summary/ \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output provider_summary_malformed_id_contract_test.py \
# 		--output-dir /home/runner/work/netbox/netbox/tests/skyramp \
# 		--overwrite \
# 		--path-params id=abc \
# 		--provider \
# 		--response-status-code 404 \
# 		--runtime local

# Import of required libraries
import skyramp
import os


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8092")

# contract test for /api/circuits/providers/{id}/summary/ GET
def test_summary_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "abc"

    # Execute Request
    summary_GET_response = client.send_request(
        url=URL,
        path="/api/circuits/providers/{id}/summary/",
        method="GET",
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert summary_GET_response.status_code == 404


if __name__ == "__main__":
    test_summary_get()
