# Generated by Skyramp v1.3.33 on 2026-07-08 02:17:27.41669437 +0000 UTC m=+364.531218824
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output provider_summary_cross_provider_isolation_integration_test.py \
# 		--output-dir /home/runner/work/netbox/netbox/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/netbox/netbox/tests/skyramp/scenario_provider_summary_cross_provider_isolation.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8092")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_5_POST_request_body = r'''{
        "name": "Provider Isolation A 9002",
        "slug": "provider-isolation-a-9002"
    }'''

    # Execute Request
    endpoint_5_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/circuits/providers/",
        method="POST",
        body=endpoint_5_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert endpoint_5_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_5_POST_response, "name") == "Provider Isolation A 9002"
    assert skyramp.get_response_value(endpoint_5_POST_response, "slug") == "provider-isolation-a-9002"
    assert skyramp.get_response_value(endpoint_5_POST_response, "id") > 0

    # Request Body
    endpoint_5_POST_1_request_body = r'''{
        "name": "Provider Isolation B 9002",
        "slug": "provider-isolation-b-9002"
    }'''

    # Execute Request
    endpoint_5_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/circuits/providers/",
        method="POST",
        body=endpoint_5_POST_1_request_body,
        headers=headers
    )

    # Generated Assertions
    assert endpoint_5_POST_1_response.status_code == 201
    assert skyramp.get_response_value(endpoint_5_POST_1_response, "name") == "Provider Isolation B 9002"
    assert skyramp.get_response_value(endpoint_5_POST_1_response, "slug") == "provider-isolation-b-9002"
    assert skyramp.get_response_value(endpoint_5_POST_1_response, "id") > 0
    assert skyramp.get_response_value(endpoint_5_POST_1_response, "id") != skyramp.get_response_value(endpoint_5_POST_response, "id")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "name": "Circuit Type Isolation 9002",
        "slug": "circuit-type-isolation-9002"
    }'''

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/circuits/circuit-types/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "Circuit Type Isolation 9002"
    assert skyramp.get_response_value(endpoint_1_POST_response, "slug") == "circuit-type-isolation-9002"
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") > 0

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "cid": "CKT-ISO-9002",
        "provider": 120,
        "type": 210
    }'''

    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/circuits/circuits/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers,
        data_override={"provider": skyramp.get_response_value(endpoint_5_POST_1_response, "id"), "type": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )

    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_2_POST_response, "cid") == "CKT-ISO-9002"
    assert skyramp.get_response_value(endpoint_2_POST_response, "provider.id") == skyramp.get_response_value(endpoint_5_POST_1_response, "id")
    assert skyramp.get_response_value(endpoint_2_POST_response, "type.id") == skyramp.get_response_value(endpoint_1_POST_response, "id")
    assert skyramp.get_response_value(endpoint_2_POST_response, "id") > 0

    # Request Body
    endpoint_3_POST_request_body = r'''{
        "account": "ACCT-ISO-9002",
        "provider": 120
    }'''

    # Execute Request
    endpoint_3_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/circuits/provider-accounts/",
        method="POST",
        body=endpoint_3_POST_request_body,
        headers=headers,
        data_override={"provider": skyramp.get_response_value(endpoint_5_POST_1_response, "id")}
    )

    # Generated Assertions
    assert endpoint_3_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_3_POST_response, "account") == "ACCT-ISO-9002"
    assert skyramp.get_response_value(endpoint_3_POST_response, "provider.id") == skyramp.get_response_value(endpoint_5_POST_1_response, "id")
    assert skyramp.get_response_value(endpoint_3_POST_response, "id") > 0

    # Request Body
    endpoint_4_POST_request_body = r'''{
        "name": "Provider Network Isolation 9002",
        "provider": 120
    }'''

    # Execute Request
    endpoint_4_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/circuits/provider-networks/",
        method="POST",
        body=endpoint_4_POST_request_body,
        headers=headers,
        data_override={"provider": skyramp.get_response_value(endpoint_5_POST_1_response, "id")}
    )

    # Generated Assertions
    assert endpoint_4_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_4_POST_response, "name") == "Provider Network Isolation 9002"
    assert skyramp.get_response_value(endpoint_4_POST_response, "provider.id") == skyramp.get_response_value(endpoint_5_POST_1_response, "id")
    assert skyramp.get_response_value(endpoint_4_POST_response, "id") > 0

    # Execute Request
    endpoint_6_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/circuits/providers/{providers}/summary/",
        method="GET",
        headers=headers,
        path_params={"providers": skyramp.get_response_value(endpoint_5_POST_response, "id")}
    )

    # Generated Assertions
    assert endpoint_6_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_6_GET_response, "circuit_count") == 0
    assert skyramp.get_response_value(endpoint_6_GET_response, "account_count") == 0
    assert skyramp.get_response_value(endpoint_6_GET_response, "network_count") == 0
    assert skyramp.get_response_value(endpoint_6_GET_response, "total_related") == 0

    # Execute Request
    endpoint_6_GET_1_response = client.send_request(
        url=URL_localhost,
        path="/api/circuits/providers/{providers}/summary/",
        method="GET",
        headers=headers,
        path_params={"providers": skyramp.get_response_value(endpoint_5_POST_1_response, "id")}
    )

    # Generated Assertions
    assert endpoint_6_GET_1_response.status_code == 200
    assert skyramp.get_response_value(endpoint_6_GET_1_response, "circuit_count") == 1
    assert skyramp.get_response_value(endpoint_6_GET_1_response, "account_count") == 1
    assert skyramp.get_response_value(endpoint_6_GET_1_response, "network_count") == 1
    assert skyramp.get_response_value(endpoint_6_GET_1_response, "total_related") == (
        skyramp.get_response_value(endpoint_6_GET_1_response, "circuit_count")
        + skyramp.get_response_value(endpoint_6_GET_1_response, "account_count")
        + skyramp.get_response_value(endpoint_6_GET_1_response, "network_count")
    )


if __name__ == "__main__":
    test_integration()
