# Generated by Skyramp v1.3.29 on 2026-06-28 23:43:40.531158343 +0000 UTC m=+235.935313166
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output provider_summary_zero_counts_integration_test.py \
# 		--output-dir /home/runner/work/netbox/netbox/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/netbox/netbox/tests/skyramp/scenario_provider-summary-zero-counts.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8092")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    providers = "1"

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "name": "Provider-ZeroTest",
        "slug": "provider-zerotest"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/circuits/providers/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "Provider-ZeroTest"
    assert skyramp.get_response_value(endpoint_1_POST_response, "slug") == "provider-zerotest"
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") > 0

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/circuits/providers/{providers}/summary/",
        method="GET",
        headers=headers,
        path_params={"providers": providers}
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_2_GET_response, "circuit_count") == 0
    assert skyramp.get_response_value(endpoint_2_GET_response, "account_count") == 0
    assert skyramp.get_response_value(endpoint_2_GET_response, "network_count") == 0
    assert skyramp.get_response_value(endpoint_2_GET_response, "total_related") == skyramp.get_response_value(endpoint_2_GET_response, "circuit_count") + skyramp.get_response_value(endpoint_2_GET_response, "account_count") + skyramp.get_response_value(endpoint_2_GET_response, "network_count")
    assert skyramp.get_response_value(endpoint_2_GET_response, "total_related") == 0


if __name__ == "__main__":
    test_integration()
