# Generated by Skyramp v1.3.33 on 2026-07-08 02:42:53.237871737 +0000 UTC m=+214.198315252
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output sites_physical_address_exact_match_filter_integration_test.py \
# 		--output-dir /home/runner/work/netbox/netbox/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/netbox/netbox/tests/skyramp/scenario_sites_physical_address_exact_match_filter.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8092")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "name": "Physical Addr Site A 1783478474",
        "physical_address": "100 Main Street, Springfield",
        "slug": "physical-addr-site-a-1783478474",
        "status": "active"
    }'''

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/dcim/sites/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "Physical Addr Site A 1783478474"
    assert skyramp.get_response_value(endpoint_1_POST_response, "slug") == "physical-addr-site-a-1783478474"
    assert skyramp.get_response_value(endpoint_1_POST_response, "physical_address") == "100 Main Street, Springfield"
    assert skyramp.get_response_value(endpoint_1_POST_response, "status.value") == "active"
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") > 0

    # Request Body
    endpoint_1_POST_1_request_body = r'''{
        "name": "Physical Addr Site B 1783478474",
        "physical_address": "100 Main Street, Springfield Heights",
        "slug": "physical-addr-site-b-1783478474",
        "status": "active"
    }'''

    # Execute Request
    endpoint_1_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/dcim/sites/",
        method="POST",
        body=endpoint_1_POST_1_request_body,
        headers=headers
    )

    # Generated Assertions
    assert endpoint_1_POST_1_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "name") == "Physical Addr Site B 1783478474"
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "slug") == "physical-addr-site-b-1783478474"
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "physical_address") == "100 Main Street, Springfield Heights"
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "status.value") == "active"
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "id") > 0

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/dcim/sites/",
        method="GET",
        headers=headers,
        query_params={"physical_address": ["100 Main Street, Springfield"]}
    )

    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_1_GET_response, "count") == 1
    assert skyramp.get_response_value(endpoint_1_GET_response, "results.0.id") == skyramp.get_response_value(endpoint_1_POST_response, "id")
    assert skyramp.get_response_value(endpoint_1_GET_response, "results.0.name") == "Physical Addr Site A 1783478474"
    assert skyramp.get_response_value(endpoint_1_GET_response, "results.0.physical_address") == "100 Main Street, Springfield"
    assert skyramp.get_response_value(endpoint_1_GET_response, "results.1") is None


if __name__ == "__main__":
    test_integration()
