# Generated by Skyramp v1.3.29 on 2026-06-28 23:47:40.99416379 +0000 UTC m=+424.016756953
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output site_physical_address_filter_happy_path_integration_test.py \
# 		--output-dir /home/runner/work/netbox/netbox/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/netbox/netbox/tests/skyramp/scenario_site-physical-address-filter-happy-path.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8092")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "name": "Skyramp Test Site PA",
        "physical_address": "999 Skyramp Test Blvd Austin TX 78701",
        "slug": "skyramp-test-site-pa"
    }'''

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/dcim/sites/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "Skyramp Test Site PA"
    assert skyramp.get_response_value(endpoint_1_POST_response, "slug") == "skyramp-test-site-pa"
    assert skyramp.get_response_value(endpoint_1_POST_response, "physical_address") == "999 Skyramp Test Blvd Austin TX 78701"
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") > 0
    assert skyramp.get_response_value(endpoint_1_POST_response, "url").startswith("http")

    # Declaration of variables — chained from POST response
    sites = str(skyramp.get_response_value(endpoint_1_POST_response, "id"))

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/dcim/sites/",
        method="GET",
        headers=headers,
        query_params={"physical_address": ["999 Skyramp Test Blvd Austin TX 78701"]}
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_1_GET_response, "count") == 1
    assert skyramp.get_response_value(endpoint_1_GET_response, "results.0.name") == "Skyramp Test Site PA"
    assert skyramp.get_response_value(endpoint_1_GET_response, "results.0.physical_address") == "999 Skyramp Test Blvd Austin TX 78701"
    assert skyramp.get_response_value(endpoint_1_GET_response, "results.0.id") == skyramp.get_response_value(endpoint_1_POST_response, "id")
    assert skyramp.get_response_value(endpoint_1_GET_response, "results.1") is None

    # Execute Request
    endpoint_2_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/dcim/sites/{sites}/",
        method="DELETE",
        headers=headers,
        path_params={"sites": sites}
    )
    # Generated Assertions
    assert endpoint_2_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
