# Generated by Skyramp v1.3.33 on 2026-07-08 02:42:55.257615559 +0000 UTC m=+216.218059074
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output sites_physical_address_updated_via_patch_integration_test.py \
# 		--output-dir /home/runner/work/netbox/netbox/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/netbox/netbox/tests/skyramp/scenario_sites_physical_address_updated_via_patch.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8092")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "name": "Physical Addr Site C 1783478474",
        "physical_address": "200 Old Address Road",
        "slug": "physical-addr-site-c-1783478474",
        "status": "active"
    }'''

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/dcim/sites/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "Physical Addr Site C 1783478474"
    assert skyramp.get_response_value(endpoint_1_POST_response, "slug") == "physical-addr-site-c-1783478474"
    assert skyramp.get_response_value(endpoint_1_POST_response, "physical_address") == "200 Old Address Road"
    assert skyramp.get_response_value(endpoint_1_POST_response, "status.value") == "active"
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") > 0

    sites = str(skyramp.get_response_value(endpoint_1_POST_response, "id"))

    # Request Body
    endpoint_2_PATCH_request_body = r'''{
        "physical_address": "300 New Address Boulevard"
    }'''

    # Execute Request
    endpoint_2_PATCH_response = client.send_request(
        url=URL_localhost,
        path="/api/dcim/sites/{sites}/",
        method="PATCH",
        body=endpoint_2_PATCH_request_body,
        headers=headers,
        path_params={"sites": sites}
    )

    # Generated Assertions
    assert endpoint_2_PATCH_response.status_code == 200
    assert skyramp.get_response_value(endpoint_2_PATCH_response, "id") == skyramp.get_response_value(endpoint_1_POST_response, "id")
    assert skyramp.get_response_value(endpoint_2_PATCH_response, "physical_address") == "300 New Address Boulevard"

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/dcim/sites/",
        method="GET",
        headers=headers,
        query_params={"physical_address": ["300 New Address Boulevard"]}
    )

    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_1_GET_response, "count") == 1
    assert skyramp.get_response_value(endpoint_1_GET_response, "results.0.id") == skyramp.get_response_value(endpoint_1_POST_response, "id")
    assert skyramp.get_response_value(endpoint_1_GET_response, "results.0.physical_address") == "300 New Address Boulevard"
    assert skyramp.get_response_value(endpoint_1_GET_response, "results.1") is None

    # Execute Request
    endpoint_1_GET_1_response = client.send_request(
        url=URL_localhost,
        path="/api/dcim/sites/",
        method="GET",
        headers=headers,
        query_params={"physical_address": ["200 Old Address Road"]}
    )

    # Generated Assertions
    assert endpoint_1_GET_1_response.status_code == 200
    assert skyramp.get_response_value(endpoint_1_GET_1_response, "count") == 0
    assert skyramp.get_response_value(endpoint_1_GET_1_response, "results.0") is None


if __name__ == "__main__":
    test_integration()
