# Generated by Skyramp v1.3.29 on 2026-06-28 23:47:27.797964515 +0000 UTC m=+410.820557658
# Command: skyramp generate contract rest http://localhost:8092/api/dcim/sites/ \
# 		--api-schema http://localhost:8092/api/schema/ \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output sites_physical_address_contract_test.py \
# 		--output-dir /home/runner/work/netbox/netbox/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--query-params physical_address=123 Main St \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8092")

# contract test for /api/dcim/sites/ GET
def test_sites_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_sites_GET_response_body = r'''{
        "count": 0,
        "next": null,
        "previous": null,
        "results": []
    }'''

    # Execute Request
    sites_GET_response = client.send_request(
        url=URL,
        path="/api/dcim/sites/",
        method="GET",
        headers=headers,
        query_params={"physical_address": "123 Main St"}
    )

    # Generated Assertions
    assert sites_GET_response.status_code == 200
    assert skyramp.check_schema(sites_GET_response, expected_sites_GET_response_body)
    assert skyramp.get_response_value(sites_GET_response, "count") is not None
    assert skyramp.get_response_value(sites_GET_response, "count") >= 0
    assert skyramp.get_response_value(sites_GET_response, "count") == 0


if __name__ == "__main__":
    test_sites_get()
