# Generated by Skyramp v1.3.29 on 2026-06-25 22:31:55.674536614 +0000 UTC m=+279.223211891
# Command: skyramp generate contract rest http://localhost:8092/api/users/tokens/provision/ \
# 		--api-schema http://localhost:8092/api/schema/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output token_provision_contract_test.py \
# 		--output-dir /home/runner/work/netbox/netbox/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--request-data {"username":"admin","password":"Password123!","version":1} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8092")

# contract test for /api/users/tokens/provision/ POST
def test_provision_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    provision_POST_multipart_values = [
        skyramp.MultipartParam(
            name="password",
            filename="",
            decoded=False,
            value="Password123!"
        ),
        skyramp.MultipartParam(
            name="username",
            filename="",
            decoded=False,
            value="admin"
        )
    ]
    # Request Body
    provision_POST_request_body = r'''{
        "password": "Password123!",
        "username": "admin",
        "version": 1
    }'''

    # Expected Response Body
    expected_provision_POST_response_body = r'''{
        "created": "2026-06-25T22:31:55Z",
        "display": "admin (token)",
        "display_url": "http://localhost:8092/api/users/tokens/1/",
        "id": 1,
        "key": "abc123def456abc123def456abc123def456abc1",
        "last_used": "2026-06-25T22:31:55Z",
        "url": "http://localhost:8092/api/users/tokens/1/",
        "user": {
            "display": "admin",
            "id": 1,
            "url": "http://localhost:8092/api/users/users/1/",
            "username": "admin"
        }
    }'''

    # Execute Request
    provision_POST_response = client.send_request(
        url=URL,
        path="/api/users/tokens/provision/",
        method="POST",
        body=provision_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert provision_POST_response.status_code == 201
    assert skyramp.check_schema(provision_POST_response, expected_provision_POST_response_body)
    assert skyramp.get_response_value(provision_POST_response, "created") is not None
    assert skyramp.get_response_value(provision_POST_response, "display") is not None
    assert skyramp.get_response_value(provision_POST_response, "display_url") is not None
    assert skyramp.get_response_value(provision_POST_response, "id") > 0
    assert skyramp.get_response_value(provision_POST_response, "key") is not None
    assert skyramp.get_response_value(provision_POST_response, "url").startswith("http://")
    assert skyramp.get_response_value(provision_POST_response, "user.username") == "admin"
    assert skyramp.get_response_value(provision_POST_response, "user.id") > 0


if __name__ == "__main__":
    test_provision_post()
